language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kamalaker2004/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true kamalaker2004/reactapp npm run test
